apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - vs.yaml
helmCharts:
- name: grafana
  includeCRDs: true
  releaseName: grafana
  version: 6.32.2
  repo: https://grafana.github.io/helm-charts