apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - pv.yaml
helmCharts:
- name: vault
  includeCRDs: true
  releaseName: vault
  version: 0.20.1
  repo: https://helm.releases.hashicorp.com
  valuesInline:
    server:
      dataStorage:
        storageClass: manual
        mountPath: "/mnt/data-vault"
    ui:
      enabled: true
      serviceType: "LoadBalancer"
