apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
helmCharts:
- name: vault
  includeCRDs: true
  releaseName: vault
  version: 0.20.1
  repo: https://helm.releases.hashicorp.com
  valuesInline:
    ui:
      enabled: true
      serviceType: "LoadBalancer"
