apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: pv-volume-vault
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data-vault
  storageClassName: manual
