apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph-cluster
resources:
  - storageclass.yaml
helmCharts:
- name: rook-ceph-cluster
  includeCRDs: true
  releaseName: rook-ceph-cluster
  version: v1.9.5
  repo: https://charts.rook.io/release
  valuesInline:
    operatorNamespace: rook-ceph
