apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - github.com/metallb/metallb//manifests?ref=v0.12.1
  - ipaddresspool.yaml

configMapGenerator:
  - name: config
    files:
      - configs/config

generatorOptions:
  disableNameSuffixHash: true