apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kiali-operator
resources:
  - vs.yaml
helmCharts:
- name: kiali-operator
  includeCRDs: true
  releaseName: kiali-operator
  version: 1.53.0
  repo: https://kiali.org/helm-charts
  valuesInline:
    cr:
      create: true
      namespace: istio-system
