apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - pv.yaml
helmCharts:
- name: prometheus
  includeCRDs: true
  releaseName: prometheus
  version: 15.5.3
  repo: https://prometheus-community.github.io/helm-charts
  valuesInline:
    alertmanager:
      persistentVolume:
        storageClass: manual
    server:
      persistentVolume:
        storageClass: manual
