apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
helmCharts:
- name: rook-ceph
  includeCRDs: true
  releaseName: rook-ceph
  version: v1.9.5
  repo: https://charts.rook.io/release
